### ISSUE TITLE
New Issue Checklist

### ISSUE THREAD

**Issue by MrOwnership** [RetroAchievements/RANews#13]
# RANews checklist

## System Requirements

- [ ] Have [Jekyll](https://jekyllrb.com/) installed. **Note:** If you're familiar with [docker](https://www.docker.com/), you don't need to install Jekyll.
- [ ] Have a way to run a bash script (native on Linux/MacOS, requires some tweaks on Windows).
- [ ] Have a git client installed.
- [ ] Optional but suggested: [Visual Studio Code](https://code.visualstudio.com/) (makes git commands easier)

##  Steps to release a new RANews issue

- [ ] create a dirs `/_issues/yyyy-mm/` and the `img` subdir

- [ ] get the `cover.png` and put it in `/_issues/yyyy-mm/img`

- [ ] change the front-matter of the `/index.html`, putting the current issue's dir in the `currentIssue` variable. Example: `currentIssue: /issues/2021-09/`

- [ ] get from Hotscrock the txt file with data for RnR, Hotcheevs and ArtUpdates.
    - [ ] run the `generate-articles.sh` script with the txt file to generate the 3 articles.

- [ ] get the top mastery images and put them in `/_issues/yyyy-mm/img`
    - [ ] The images' filenames **MUST** follow this pattern: `top-mastery-${consoleNickname}`. See examples [here](https://github.com/RetroAchievements/RANews/tree/master/_issues/2021-09/img)

- [ ] articles 
  - [ ] intro - talk a bit about what to expect from this issue
  - [ ] editorial - something the "editor" want to say to the readers
  - [ ] hotcheevs monthly - copy'n'paste generated article
  - [ ] revisions'n'rescores - copy'n'paste generated article
  - [ ] art updates - copy'n'paste generated article
  - [ ] top players - copy'n'paste Xymjak's file
  - [ ] play-this-set 10 mini-articles - get from the [wiki](https://github.com/RetroAchievements/RANews/wiki)
  - [ ] most wanted games - get data (ok), and create the images???
  - [ ] current events - HolyShinx gets data from [this forum post](https://retroachievements.org/viewtopic.php?t=9014)
  - [ ] community works - when community members do a shareable RA-related thing, we advertise in a dedicated page.
  - [ ] DevTip
  - [ ] Fun - currently SporyTike
  - [ ] RAViews
  - [ ] RAGuide - picked by ViperZang
  - [ ] custom article(s)?

- [ ] commit the changes to the repository
