### ISSUE TITLE
RANews new issue checklist

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RANews#5]
- [ ] create a dirs `/_issues/yyyy-mm/` and the `img` subdir
- [ ] get the `cover.png` and put it in `/_issues/yyyy-mm/img` **and** `/img/`.
- [ ] change the frontpage link to the latest issue to point to the latest issue.
- [ ] articles
  - [ ] intro (meleu)
  - [ ] editorial (meleu)
  - [ ] hotcheevs monthly (Hotscrock)
  - [ ] revisions/rescores/art updates (Hotscrock)
  - [ ] top players (Xymjak)
  - [ ] play-this-set 10 mini-articles (StingX2)
  - [ ] most wanted games (StingX2)
  - [ ] current events <https://retroachievements.org/viewtopic.php?t=9014>
  - [ ] community works
  - [ ] DevTip
  - [ ] Fun
  - [ ] RAViews
  - [ ] RAGuide
  - [ ] custom article(s)?
- [ ] commit the changes to the repository

**Comment by meleu** [comment]
Markdown to RA-forums conversion tricks:

- Convert markdown links to forum `[url]` links:
```
:%s/\[\([^]]\+\)\](\([^)]\+\))/[url=\2]\1[\/url]/gc
```

- convert `{% rauser username %}` to `[user=username]`:
```
:%s/{% rauser \([^ ]*\) %}/[user=\1]/gc 
```
